-- MySQL Script generated by MySQL Workbench
-- Mon Jun 17 17:30:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 22var
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 22var
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `22var` DEFAULT CHARACTER SET utf8 ;
USE `22var` ;

-- -----------------------------------------------------
-- Table `22var`.`individual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `22var`.`individual` (
  `idindividual` INT NOT NULL AUTO_INCREMENT,
  `family` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `date_birthday` DATE NOT NULL,
  `passport_series` VARCHAR(10) NOT NULL,
  `passport_id` VARCHAR(10) NOT NULL,
  `passport_issued_by` VARCHAR(45) NOT NULL,
  `date_issue` DATE NOT NULL,
  PRIMARY KEY (`idindividual`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `22var`.`job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `22var`.`job` (
  `idjob` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `shortname` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idjob`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `22var`.`type_of_legalentity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `22var`.`type_of_legalentity` (
  `idtype_of_legalentity` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `shortname` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idtype_of_legalentity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `22var`.`legalentity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `22var`.`legalentity` (
  `idlegalentity` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `shortname` VARCHAR(45) NOT NULL,
  `type_of_legalentity_idtype_of_legalentity` INT NOT NULL,
  PRIMARY KEY (`idlegalentity`),
  INDEX `fk_legalentity_type_of_legalentity1_idx` (`type_of_legalentity_idtype_of_legalentity` ASC) VISIBLE,
  CONSTRAINT `fk_legalentity_type_of_legalentity1`
    FOREIGN KEY (`type_of_legalentity_idtype_of_legalentity`)
    REFERENCES `22var`.`type_of_legalentity` (`idtype_of_legalentity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `22var`.`laborcontract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `22var`.`laborcontract` (
  `idlaborcontract` INT NOT NULL AUTO_INCREMENT,
  `date_start` DATE NOT NULL,
  `date_end` DATE NOT NULL,
  `salary` DECIMAL(10) NOT NULL,
  `individual_idindividual` INT NOT NULL,
  `job_idjob` INT NOT NULL,
  `legalentity_idlegalentity` INT NOT NULL,
  PRIMARY KEY (`idlaborcontract`),
  INDEX `fk_laborcontract_individual1_idx` (`individual_idindividual` ASC) VISIBLE,
  INDEX `fk_laborcontract_job1_idx` (`job_idjob` ASC) VISIBLE,
  INDEX `fk_laborcontract_legalentity1_idx` (`legalentity_idlegalentity` ASC) VISIBLE,
  CONSTRAINT `fk_laborcontract_individual1`
    FOREIGN KEY (`individual_idindividual`)
    REFERENCES `22var`.`individual` (`idindividual`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_laborcontract_job1`
    FOREIGN KEY (`job_idjob`)
    REFERENCES `22var`.`job` (`idjob`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_laborcontract_legalentity1`
    FOREIGN KEY (`legalentity_idlegalentity`)
    REFERENCES `22var`.`legalentity` (`idlegalentity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `22var`.`settlement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `22var`.`settlement` (
  `idsettlement` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `shortname` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idsettlement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `22var`.`type_of_motorship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `22var`.`type_of_motorship` (
  `idtype_of_motorship` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `shortname` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idtype_of_motorship`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `22var`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `22var`.`brand` (
  `idbrand` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `shortname` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idbrand`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `22var`.`model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `22var`.`model` (
  `idmodel` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `brand_idbrand` INT NOT NULL,
  PRIMARY KEY (`idmodel`),
  INDEX `fk_model_brand1_idx` (`brand_idbrand` ASC) VISIBLE,
  CONSTRAINT `fk_model_brand1`
    FOREIGN KEY (`brand_idbrand`)
    REFERENCES `22var`.`brand` (`idbrand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `22var`.`country_manufactory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `22var`.`country_manufactory` (
  `idcountry` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `abbreviation` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idcountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `22var`.`motorship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `22var`.`motorship` (
  `idmotorship` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `capacity` INT NOT NULL,
  `type_of_motorship_idtype_of_motorship` INT NOT NULL,
  `model_idmodel` INT NOT NULL,
  `country_manufactory_idcountry` INT NOT NULL,
  PRIMARY KEY (`idmotorship`),
  INDEX `fk_motorship_type_of_motorship1_idx` (`type_of_motorship_idtype_of_motorship` ASC) VISIBLE,
  INDEX `fk_motorship_model1_idx` (`model_idmodel` ASC) VISIBLE,
  INDEX `fk_motorship_country_manufactory1_idx` (`country_manufactory_idcountry` ASC) VISIBLE,
  CONSTRAINT `fk_motorship_type_of_motorship1`
    FOREIGN KEY (`type_of_motorship_idtype_of_motorship`)
    REFERENCES `22var`.`type_of_motorship` (`idtype_of_motorship`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_motorship_model1`
    FOREIGN KEY (`model_idmodel`)
    REFERENCES `22var`.`model` (`idmodel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_motorship_country_manufactory1`
    FOREIGN KEY (`country_manufactory_idcountry`)
    REFERENCES `22var`.`country_manufactory` (`idcountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `22var`.`voyage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `22var`.`voyage` (
  `idvoyage` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `duration` TIME NOT NULL,
  `settlement_idsettlement` INT NOT NULL,
  `settlement_idsettlement1` INT NOT NULL,
  `motorship_idmotorship` INT NOT NULL,
  PRIMARY KEY (`idvoyage`),
  INDEX `fk_voyage_settlement1_idx` (`settlement_idsettlement` ASC) VISIBLE,
  INDEX `fk_voyage_settlement2_idx` (`settlement_idsettlement1` ASC) VISIBLE,
  INDEX `fk_voyage_motorship1_idx` (`motorship_idmotorship` ASC) VISIBLE,
  CONSTRAINT `fk_voyage_settlement1`
    FOREIGN KEY (`settlement_idsettlement`)
    REFERENCES `22var`.`settlement` (`idsettlement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voyage_settlement2`
    FOREIGN KEY (`settlement_idsettlement1`)
    REFERENCES `22var`.`settlement` (`idsettlement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voyage_motorship1`
    FOREIGN KEY (`motorship_idmotorship`)
    REFERENCES `22var`.`motorship` (`idmotorship`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `22var`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `22var`.`service` (
  `idservice` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idservice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `22var`.`measure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `22var`.`measure` (
  `idmeasure` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `shortname` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idmeasure`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `22var`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `22var`.`ticket` (
  `idticket` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `price` DECIMAL NOT NULL,
  `date_departure` DATE NOT NULL,
  `time_departure` TIME NOT NULL,
  `date_of_sale` DATE NOT NULL,
  `cabinnumber` INT NOT NULL,
  `individual_idindividual` INT NOT NULL,
  `laborcontract_idlaborcontract` INT NOT NULL,
  `voyage_idvoyage` INT NOT NULL,
  `service_idservice` INT NOT NULL,
  `measure_idmeasure` INT NOT NULL,
  PRIMARY KEY (`idticket`),
  INDEX `fk_ticket_individual_idx` (`individual_idindividual` ASC) VISIBLE,
  INDEX `fk_ticket_laborcontract1_idx` (`laborcontract_idlaborcontract` ASC) VISIBLE,
  INDEX `fk_ticket_voyage1_idx` (`voyage_idvoyage` ASC) VISIBLE,
  INDEX `fk_ticket_service1_idx` (`service_idservice` ASC) VISIBLE,
  INDEX `fk_ticket_measure1_idx` (`measure_idmeasure` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_individual`
    FOREIGN KEY (`individual_idindividual`)
    REFERENCES `22var`.`individual` (`idindividual`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_laborcontract1`
    FOREIGN KEY (`laborcontract_idlaborcontract`)
    REFERENCES `22var`.`laborcontract` (`idlaborcontract`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_voyage1`
    FOREIGN KEY (`voyage_idvoyage`)
    REFERENCES `22var`.`voyage` (`idvoyage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_service1`
    FOREIGN KEY (`service_idservice`)
    REFERENCES `22var`.`service` (`idservice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_measure1`
    FOREIGN KEY (`measure_idmeasure`)
    REFERENCES `22var`.`measure` (`idmeasure`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
